spring:
  application:
      name: microservice-tcc-provider-service

  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  zipkin:
      service:
        name: microservice-sleuth-zipkin-service
  sleuth:
      sampler:
        percentage: 1.0

druid:
      url: jdbc:mysql://localhost:3306/springCloud?characterEncoding=utf8&useSSL=true
      driver-class: com.mysql.jdbc.Driver
      username: root
      password: 111111
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      filters: stat,wall,slf4j


server:
  port: 8086


eureka:
  client:
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka

mybatis:
  type-aliases-package: com.springCloud.domain
  mapper-locations: classpath:mapper/*.xml
  mappers: com.springCloud.dao.**
  configuration-properties:
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true


logging.level.org.springframework.security: DEBUG

logging.leve.org.springframework: DEBUG






