server:
  port: 8761



eureka:
  environment: prod
  datacenter: Data Center:8761
  server:
    renewal-percent-threshold: 0.0
  client:
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1



spring:
  application:
    name: microservice-discovery-eureka-service
  security:
    user:
      name: admin
      password: admin

