spring:
  profiles:
    active: default


  application:
    name: microservice-config-service


  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/Joeysin/Config-Repo.git
#          searchPaths: blob/master
#          username: username
#          password: password
      label: master


  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  bus:
    trace:
      enabled: true


server:
  port: 8888


eureka:
  client:
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@eureka:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

#关闭安全验证
management:
  security:
     enabled: false





