spring:
  application:
      name: microservice-order-service-with-sleuthZipkin-backup

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    service:
      name: microservice-sleuth-zipkin-service
  sleuth:
        sampler:
          percentage: 1.0

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10

server:
    port: 8086






