server:
  port: 9411

#表示zipkin数据存储方式是mysql
zipkin:
  storage:
    type: mysql

spring:
  application:
      name: microservice-sleuth-zipkin-service

  sleuth:
      enabled: true

  datasource:
      url: jdbc:mysql://localhost:3306/zipkin?characterEncoding=utf8&useSSL=false
      username: root
      password: 111111
      driver-class-name: com.mysql.jdbc.Driver
      initialize: true
      continue-on-error: true

  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka







