spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  application:
      name: microservice-zuul-gateway-service
  cloud:
      loadbalancer:
            retry:
              enabled: true  #启动重试机制
#    config:
#      uri: http://${config.host:192.168.1.140}:${config.port:8888}

server:
  port: 8080


eureka:
  client:
#    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@eureka:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10

ribbon:
    OkToRetryOnAllOperations: false # 是否对所有请求都进行重试
    MaxAutoRetriesNextServer: 2   #重试切换实例次数
    MaxAutoRetries: 1     #重试次数
    ConnectTimeout: 2000
    ReadTimeout: 6000


zuul:
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: microservice-oauth2-service
    order:
      path: /order/**
      sensitiveHeaders:
      serviceId: microservice-order-service
    config:
      path: /config/**
      sensitiveHeaders:
      serviceId: microservice-config-service


  add-proxy-headers: true

security:
  oauth2:
    client:
      access-token-uri: http://127.0.0.1:8080/uaa/oauth/token
      user-authorization-uri: http://127.0.0.1:8080/uaa/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://127.0.0.1:8080/uaa/user
      prefer-token-info: false

#该时间必须大于Ribbon的readTimeOut，因为默认为一秒，会先触发断路器
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 7000