spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  application:
      name: microservice-zuul-gateway-service
#  cloud:
#    config:
#      uri: http://${config.host:192.168.1.140}:${config.port:8888}

server:
  port: 8080


eureka:
  client:
#    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10

ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 60000


zuul:
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: microservice-oauth2-service
    order:
      path: /order/**
      sensitiveHeaders:
      serviceId: microservice-order-service
    config:
      path: /config/**
      sensitiveHeaders:
      serviceId: microservice-config-service


  add-proxy-headers: true

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/uaa/oauth/token
      user-authorization-uri: http://localhost:8080/uaa/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:8080/uaa/user
      prefer-token-info: false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 70000